language: node_js

node_js:
  - '0.12'
  - '0.11'
  - '0.10'

services: mongodb

# after_success: npm run coveralls

deploy:
  provider: heroku
  api_key:
    secure: GtdKMYvxE9XE4nbcANpS2juBPZE6nRQw4qS84L8rUpkgFoTJXTH7HEMrdEi9Te5KcJIempCKbTRa/GXkKVP0OLy7S0Aox66eiwd4qlVQzPkZpqp2LI7ltftDg+SoKni4+DX+7euZanc3v7exhbEMs/RRT3eAZ5dUItF2FC1sCW8=
  app: pacific-beach-3008
  on:
    branch: master
    node: '0.12'

before_script:
  - npm install -g bower
  - bower install
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

script: 
  - "node_modules/.bin/karma start karma.conf.js --no-auto-watch --single-run --reporters=dots && node_modules/.bin/mocha"